spring:
  profiles:
    active: dev
  application:
    name: opportune
  lifecycle:
    timeout-per-shutdown-phase: 30s
  jpa:
    open-in-view: false

server:
  shutdown: graceful
  include-stacktrace: never

springdoc:
  swagger-ui:
    docExpansion: none
    tags-sorter: alpha
    operations-sorter: alpha

application:
  info:
    name: \${spring.application.name}
    version: ${version}
    description: ${description}
    license: Apache-2.0 license
    website: \${application.info.github-url}
    github-url: https://github.com/GLinBoy/opportune
    license-url: https://github.com/GLinBoy/opportune/blob/main/LICENSE.md
    servers:
      - url: http://localhost:\${server.port}
        description: local server
