spring:
  profiles:
    active: dev
  application:
    name: opportune
  lifecycle:
    timeout-per-shutdown-phase: 30s
  jpa:
    open-in-view: false

server:
  shutdown: graceful
  include-stacktrace: never

springdoc:
  swagger-ui:
    docExpansion: none
    tags-sorter: alpha
    operations-sorter: alpha

application:
  info:
    name: \${spring.application.name}
    version: ${version}
    description: ${description}
    license: Apache-2.0 license
    website: \${OPPORTUNE_WEB_ADDRESS:http://localhost:\${server.port}}
    github-url: https://github.com/GLinBoy/opportune
    license-url: https://github.com/GLinBoy/opportune/blob/main/LICENSE.md
    servers:
      - url: \${OPPORTUNE_WEB_ADDRESS:http://localhost:\${server.port}}
        description: Application URL
  security:
    content-security-policy: "default-src 'self'; frame-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://storage.googleapis.com; style-src 'self' https://fonts.googleapis.com 'unsafe-inline'; img-src 'self' https://www.gravatar.com data:; font-src 'self' https://fonts.gstatic.com data:"
    authentication:
      jwt:
        base64-secret: \${OPPORTUNE_JWT_SECRET}
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
