package com.glinboy.opportune.enums
enum class RevocationReason {
	USER_INITIATED,
	USER_ALL_SESSIONS,
	PASSWORD_CHANGE,
	SUSPICIOUS_ACTIVITY,
	ADMIN_ACTION,
	ACCOUNT_SUSPENDED,
	DEVICE_LOST_OR_STOLEN,
	SECURITY_INCIDENT,
	OTHER
}
