export enum RevocationReason {
  USER_INITIATED = 'USER_INITIATED',
  USER_ALL_SESSIONS = 'USER_ALL_SESSIONS',
  PASSWORD_CHANGE = 'PASSWORD_CHANGE',
  SUSPICIOUS_ACTIVITY = 'SUSPICIOUS_ACTIVITY',
  ADMIN_ACTION = 'ADMIN_ACTION',
  ACCOUNT_SUSPENDED = 'ACCOUNT_SUSPENDED',
  DEVICE_LOST_OR_STOLEN = 'DEVICE_LOST_OR_STOLEN',
  SECURITY_INCIDENT = 'SECURITY_INCIDENT',
  OTHER = 'OTHER'
}
